[versions]
agp = "8.9.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
gmsAds = "23.4.0"
ucrop = "2.2.10"
googleServices = "4.4.4"
firebaseBom = "33.5.1"
playServicesAuth = "21.2.0"
mpandroidchart = "v3.1.0"
workmanager = "2.10.0"
swiperefreshlayout = "1.1.0"
exoplayer = "2.19.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "gmsAds" }
ucrop = { group = "com.github.yalantis", name = "ucrop", version.ref = "ucrop" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-database = { group = "com.google.firebase", name = "firebase-database" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
play-services-auth-lib = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpandroidchart" }
konfetti = { group = "nl.dionsegijn", name = "konfetti-xml", version = "2.0.4" }
workmanager = { group = "androidx.work", name = "work-runtime", version.ref = "workmanager" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
exoplayer = { group = "com.google.android.exoplayer", name = "exoplayer", version.ref = "exoplayer" }
exoplayer-ui = { group = "com.google.android.exoplayer", name = "exoplayer-ui", version.ref = "exoplayer" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
